### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by narc-Ontakac2** [timescale/pg_influx#18]
My influx listener crashes on startup:
```
postgres=# CREATE EXTENSION influx;
CREATE EXTENSION
postgres=# SELECT pg_sleep(1) FROM worker_launch('db_worker', 4711::text);
HINWEIS:  background worker started
DETAIL:  pid=81717
WARNUNG:  Verbindung wird abgebrochen wegen Absturz eines anderen Serverprozesses
DETAIL:  Der Postmaster hat diesen Serverprozess angewiesen, die aktuelle Transaktion zurückzurollen und die Sitzung zu beenden, weil ein anderer Serverprozess abnormal beendet wurde und möglicherweise das Shared Memory verfälscht hat.
```
This happens on a Debian  bookworm where I still have a Postgres 13 installed. Do you have any hints on how to debug this? How can I get a core dump?

**Comment by mkindahl** [comment]
Is this related to #14 ?

**Comment by narc-Ontakac2** [comment]
Going to the git HEAD fixes it. I used 0.3 because there was no 0.4 back then.

**Comment by mkindahl** [comment]
> Going to the git HEAD fixes it. I used 0.3 because there was no 0.4 back then.

Great! Thanks for reporting and checking.
